name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '20 3 * * *'

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - app: avahi-reflector
            architectures: '["aarch64", "amd64"]'
          - app: flicd
            architectures: '["aarch64", "amd64"]'
          - app: keepalived
            architectures: '["aarch64", "amd64"]'
          - app: picamera
            architectures: '["aarch64"]'
          - app: tailscale
            architectures: '["aarch64", "amd64"]'
          - app: zabbix-agent
            architectures: '["aarch64", "amd64"]'
          - app: zabbix-agent2
            architectures: '["aarch64", "amd64"]'
    uses: ./.github/workflows/build-app.yml
    with:
      app: ${{ matrix.app }}
      architectures: ${{ matrix.architectures }}
    secrets: inherit
