name: AIS-catcher
version: 0.1.11
slug: ais-catcher
description: Receive and share AIS traffic with an RTL-SDR and AIS-catcher
url: https://github.com/pschmitt/home-assistant-apps/tree/main/ais-catcher
image: ghcr.io/pschmitt/{arch}-home-assistant-app-ais-catcher
arch:
  - amd64
  - aarch64
startup: application
boot: auto
init: false
stage: experimental
usb: true
ingress: true
ingress_port: 8100
ingress_stream: true
panel_icon: mdi:ship-wheel
panel_title: AIS-catcher
timeout: 30
services:
  - mqtt:want

options:
  receiver:
    gain: auto
    ppm: 0
    rtlagc: false
    sample_rate: 1536000
    bandwidth: 192000
    channel: AB
  antenna:
    enabled: false
    latitude: 0.0
    longitude: 0.0
  web:
    enabled: true
  nmea:
    udp_outputs: []
    tcp_outputs: []
  mqtt:
    enabled: false
    topic: ais-catcher/ais
    msgformat: JSON_FULL
    qos: 0
    client_id: ais-catcher
  aishub:
    enabled: false
    host: ""
    port: 0
  aiscatcher_share:
    enabled: false
    key: ""
  log_level: info

schema:
  receiver:
    gain: str
    ppm: int(-150,150)
    rtlagc: bool
    sample_rate: int(12500,12288000)
    bandwidth: int(0,1000000)
    channel: list(AB|CD)
  antenna:
    enabled: bool
    latitude: float(-90,90)
    longitude: float(-180,180)
  web:
    enabled: bool
  nmea:
    udp_outputs:
      - host: str
        port: int(1,65535)
    tcp_outputs:
      - host: str
        port: int(1,65535)
  mqtt:
    enabled: bool
    topic: str
    msgformat: list(NMEA|JSON_NMEA|JSON_FULL)
    qos: int(0,2)
    client_id: str
  aishub:
    enabled: bool
    host: str
    port: int(0,65535)
  aiscatcher_share:
    enabled: bool
    key: password
  log_level: list(default|debug|info|warning|error|critical)
